layout: single
style: dark
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name


topics:
  - name: Threat Analysis
    image_url: https://user-images.githubusercontent.com/38113471/90684086-cf217d80-e224-11ea-9e92-754c36524777.png
    
  - name: Penetration Testing
    image_url: https://www.compass-security.com/fileadmin/Datein/Bilder/penetration-testing-lg.png

  - name: Social Engineering
    image_url: https://cdn1.iconfinder.com/data/icons/hitech-business/512/brain_surgery-512.png



social_media:
  linkedin: "rootsaadbaig"
theme: jekyll-theme-midnight