layout: single
style: dark
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name


topics:
  - name: Theat Analysis
    image_url: https://www.iotworldtoday.com/files/2020/01/GettyImages-1145882183.jpg

  - name: Penetration Testing
    image_url: https://images.idgesg.net/images/article/2019/06/cso_breakthrough_penetration_testing_hammer_hitting_glass_by_photodisc_gettyimages-bu010600_binary_code_by_metamorworks_gettyimages-1029147330_2400x1600-100798328-large.jpg

  - name: Remediation and Compliance
    image_url: https://cdn.lynda.com/course/748580/748580-637199656053673141-16x9.jpg



social_media:
  linkedin: "rootsaadbaig"
theme: jekyll-theme-midnight